class list {
  List<String> category = [
    "Latest & Trending",
    "Popular Shows",
    "Movies Recommended For You",
    "Shows Recommended For You",
    "Popular Movies",
    "Best of Foreign Shows Dubbed",
    "Hotstar Specials",
    "New on Disney+ Hotstar",
    "Multiplex Movies",
    "Quix Shows",
  ];

  List<String> pageview = ["1.webp", "2.webp", "3.webp", "4.webp", "5.webp"];

  List<String> latest_trending_1 = [
    "1_latest&trending/1.webp",
    "1_latest&trending/2.webp",
    "1_latest&trending/3.webp",
    "1_latest&trending/4.webp",
    "1_latest&trending/5.webp",
    "1_latest&trending/6.webp",
    "1_latest&trending/7.webp",
    "1_latest&trending/8.webp",
    "1_latest&trending/9.webp",
    "1_latest&trending/10.webp",
    "1_latest&trending/11.webp",
    "1_latest&trending/12.webp",
    "1_latest&trending/13.webp",
    "1_latest&trending/14.webp",
    "1_latest&trending/15.webp",
    "1_latest&trending/16.webp",
    "1_latest&trending/17.webp",
    "1_latest&trending/18.webp",
    "1_latest&trending/19.webp",
    "1_latest&trending/20.webp",
    "1_latest&trending/21.webp",
  ];

  List<String> popular_show_2 = [
    "2_popular shows/1.webp",
    "2_popular shows/2.webp",
    "2_popular shows/3.webp",
    "2_popular shows/4.webp",
    "2_popular shows/5.webp",
    "2_popular shows/6.webp",
    "2_popular shows/7.webp",
    "2_popular shows/8.webp",
    "2_popular shows/9.webp",
    "2_popular shows/10.webp",
    "2_popular shows/11.webp",
    "2_popular shows/12.webp",
    "2_popular shows/13.webp",
    "2_popular shows/14.webp",
    "2_popular shows/15.webp",
    "2_popular shows/16.webp",
    "2_popular shows/17.webp",
    "2_popular shows/18.webp",
    "2_popular shows/19.webp",
    "2_popular shows/20.webp",
    "2_popular shows/21.webp",
    "2_popular shows/22.webp",
    "2_popular shows/23.webp",
    "2_popular shows/24.webp",
    "2_popular shows/25.webp",
    "2_popular shows/26.webp",
    "2_popular shows/27.webp",
    "2_popular shows/28.webp",
    "2_popular shows/29.webp",
    "2_popular shows/30.webp",
    "2_popular shows/31.webp",
    "2_popular shows/32.webp",
    "2_popular shows/33.webp",
    "2_popular shows/34.webp",
    "2_popular shows/35.webp",
    "2_popular shows/36.webp",
    "2_popular shows/37.webp",
    "2_popular shows/38.webp",
    "2_popular shows/39.webp",
    "2_popular shows/40.webp"
  ];
  List<String> movie_recomended_3 = [
    "3_movie recomended/1.webp",
    "3_movie recomended/2.webp",
    "3_movie recomended/3.webp",
    "3_movie recomended/4.webp",
    "3_movie recomended/5.webp",
    "3_movie recomended/6.webp",
    "3_movie recomended/7.webp",
    "3_movie recomended/8.webp",
    "3_movie recomended/9.webp",
    "3_movie recomended/10.webp",
    "3_movie recomended/11.webp",
    "3_movie recomended/12.webp",
    "3_movie recomended/13.webp",
    "3_movie recomended/14.webp",
    "3_movie recomended/15.webp",
    "3_movie recomended/16.webp",
    "3_movie recomended/17.webp",
    "3_movie recomended/18.webp",
    "3_movie recomended/19.webp",
    "3_movie recomended/20.webp",
    "3_movie recomended/21.webp",
    "3_movie recomended/22.webp",
    "3_movie recomended/23.webp",
    "3_movie recomended/24.webp",
    "3_movie recomended/25.webp",
    "3_movie recomended/26.webp",
    "3_movie recomended/27.webp",
    "3_movie recomended/28.webp",
    "3_movie recomended/29.webp",
    "3_movie recomended/30.webp",
    "3_movie recomended/31.webp",
    "3_movie recomended/32.webp",
    "3_movie recomended/33.webp",
    "3_movie recomended/34.webp",
    "3_movie recomended/35.webp",
    "3_movie recomended/36.webp",
    "3_movie recomended/37.webp",
    "3_movie recomended/38.webp",
    "3_movie recomended/39.webp",
    "3_movie recomended/40.webp"
  ];
  List<String> show_recomended_4 = [
    "4_show recomended/1.webp",
    "4_show recomended/2.webp",
    "4_show recomended/3.webp",
    "4_show recomended/4.webp",
    "4_show recomended/5.webp",
    "4_show recomended/6.webp",
    "4_show recomended/7.webp",
    "4_show recomended/8.webp",
    "4_show recomended/9.webp",
    "4_show recomended/10.webp",
    "4_show recomended/11.webp",
    "4_show recomended/12.webp",
    "4_show recomended/13.webp",
    "4_show recomended/14.webp",
    "4_show recomended/15.webp",
    "4_show recomended/16.webp",
    "4_show recomended/17.webp",
    "4_show recomended/18.webp",
    "4_show recomended/19.webp",
    "4_show recomended/20.webp",
    "4_show recomended/21.webp",
    "4_show recomended/22.webp",
    "4_show recomended/23.webp",
    "4_show recomended/24.webp",
    "4_show recomended/25.webp",
    "4_show recomended/26.webp",
    "4_show recomended/27.webp",
    "4_show recomended/28.webp",
    "4_show recomended/29.webp",
    "4_show recomended/30.webp",
    "4_show recomended/31.webp",
    "4_show recomended/32.webp",
    "4_show recomended/33.webp",
    "4_show recomended/34.webp",
    "4_show recomended/35.webp",
    "4_show recomended/36.webp",
    "4_show recomended/37.webp",
    "4_show recomended/38.webp",
    "4_show recomended/39.webp",
    "4_show recomended/40.webp"
  ];
  List<String> popular_movie_5 = [
    "5_popular movies/1.webp",
    "5_popular movies/2.webp",
    "5_popular movies/3.webp",
    "5_popular movies/4.webp",
    "5_popular movies/5.webp",
    "5_popular movies/6.webp",
    "5_popular movies/7.webp",
    "5_popular movies/8.webp",
    "5_popular movies/9.webp",
    "5_popular movies/10.webp",
    "5_popular movies/11.webp",
    "5_popular movies/12.webp",
    "5_popular movies/13.webp",
    "5_popular movies/14.webp",
    "5_popular movies/15.webp",
    "5_popular movies/16.webp",
    "5_popular movies/17.webp",
    "5_popular movies/18.webp",
    "5_popular movies/19.webp",
    "5_popular movies/20.webp",
    "5_popular movies/21.webp",
    "5_popular movies/22.webp",
    "5_popular movies/23.webp",
    "5_popular movies/24.webp",
    "5_popular movies/25.webp",
    "5_popular movies/26.webp",
    "5_popular movies/27.webp",
    "5_popular movies/28.webp",
    "5_popular movies/29.webp",
    "5_popular movies/30.webp",
    "5_popular movies/31.webp",
    "5_popular movies/32.webp",
    "5_popular movies/33.webp",
    "5_popular movies/34.webp",
    "5_popular movies/35.webp",
    "5_popular movies/36.webp",
    "5_popular movies/37.webp",
    "5_popular movies/38.webp",
    "5_popular movies/39.webp",
    "5_popular movies/40.webp"
  ];
  List<String> foreign_dubbed_6 = [
    "6_foreign dubbed/1.webp",
    "6_foreign dubbed/2.webp",
    "6_foreign dubbed/3.webp",
    "6_foreign dubbed/4.webp",
    "6_foreign dubbed/5.webp"
  ];
  List<String> hotstar_special_7 = [
    "7_hotstar special/1.webp",
    "7_hotstar special/2.webp",
    "7_hotstar special/3.webp",
    "7_hotstar special/4.webp",
    "7_hotstar special/5.webp",
    "7_hotstar special/6.webp",
    "7_hotstar special/7.webp",
    "7_hotstar special/8.webp",
    "7_hotstar special/9.webp",
    "7_hotstar special/10.webp",
    "7_hotstar special/11.webp",
    "7_hotstar special/12.webp",
    "7_hotstar special/13.webp"
  ];
  List<String> newonhotstar_8 = [
    "8_new on hotstar/1.webp",
    "8_new on hotstar/2.webp",
    "8_new on hotstar/3.webp",
    "8_new on hotstar/4.webp",
    "8_new on hotstar/5.webp",
    "8_new on hotstar/6.webp",
    "8_new on hotstar/7.webp",
    "8_new on hotstar/8.webp",
    "8_new on hotstar/9.webp",
    "8_new on hotstar/10.webp",
    "8_new on hotstar/11.webp",
    "8_new on hotstar/12.webp",
    "8_new on hotstar/13.webp",
    "8_new on hotstar/14.webp",
    "8_new on hotstar/15.webp",
    "8_new on hotstar/16.webp",
    "8_new on hotstar/17.webp",
    "8_new on hotstar/18.webp",
    "8_new on hotstar/19.webp",
    "8_new on hotstar/20.webp",
    "8_new on hotstar/21.webp",
    "8_new on hotstar/22.webp",
    "8_new on hotstar/23.webp",
    "8_new on hotstar/24.webp",
    "8_new on hotstar/25.webp",
    "8_new on hotstar/26.webp",
    "8_new on hotstar/27.webp",
    "8_new on hotstar/28.webp",
    "8_new on hotstar/29.webp",
    "8_new on hotstar/30.webp",
    "8_new on hotstar/31.webp",
    "8_new on hotstar/32.webp",
    "8_new on hotstar/33.webp",
    "8_new on hotstar/34.webp",
    "8_new on hotstar/35.webp",
    "8_new on hotstar/36.webp",
    "8_new on hotstar/37.webp",
    "8_new on hotstar/38.webp",
    "8_new on hotstar/39.webp",
    "8_new on hotstar/40.webp",
    "8_new on hotstar/41.webp",
    "8_new on hotstar/42.webp",
    "8_new on hotstar/43.webp",
    "8_new on hotstar/44.webp",
    "8_new on hotstar/45.webp",
    "8_new on hotstar/46.webp",
    "8_new on hotstar/47.webp",
    "8_new on hotstar/48.webp",
    "8_new on hotstar/49.webp",
    "8_new on hotstar/50.webp",
  ];
  List<String> multiplex_movie_9 = [
    "9_multiplex_movies/1.webp",
    "9_multiplex_movies/2.webp",
    "9_multiplex_movies/3.webp",
    "9_multiplex_movies/4.webp",
    "9_multiplex_movies/5.webp",
    "9_multiplex_movies/6.webp",
    "9_multiplex_movies/7.webp",
    "9_multiplex_movies/8.webp",
    "9_multiplex_movies/9.webp",
    "9_multiplex_movies/10.webp",
    "9_multiplex_movies/11.webp",
    "9_multiplex_movies/12.webp",
    "9_multiplex_movies/13.webp",
    "9_multiplex_movies/14.webp",
    "9_multiplex_movies/15.webp",
    "9_multiplex_movies/16.webp",
    "9_multiplex_movies/17.webp",
    "9_multiplex_movies/18.webp",
    "9_multiplex_movies/19.webp",
    "9_multiplex_movies/20.webp",
    "9_multiplex_movies/21.webp",
    "9_multiplex_movies/22.webp",
    "9_multiplex_movies/23.webp",
    "9_multiplex_movies/24.webp",
    "9_multiplex_movies/25.webp",
    "9_multiplex_movies/26.webp",
    "9_multiplex_movies/27.webp",
    "9_multiplex_movies/28.webp",
    "9_multiplex_movies/29.webp",
    "9_multiplex_movies/30.webp"
  ];
  List<String> quix_show_10 = [
    "10_quix show/1.webp",
    "10_quix show/2.webp",
    "10_quix show/3.webp",
    "10_quix show/4.webp",
    "10_quix show/5.webp",
    "10_quix show/6.webp",
    "10_quix show/7.webp",
    "10_quix show/8.webp",
    "10_quix show/9.webp",
    "10_quix show/10.webp",
    "10_quix show/11.webp",
    "10_quix show/12.webp",
    "10_quix show/13.webp",
    "10_quix show/14.webp",
    "10_quix show/15.webp",
    "10_quix show/16.webp",
    "10_quix show/17.webp",
    "10_quix show/18.webp"
  ];

  List<String> title = [
    "Downloads",
    "Watchlist",
    "Prizes",
    "Channels",
    "Languages",
    "Genres",
    "Preferences",
    "Help"
  ];
  List<String> subtitle = [
    "Watch videos offline",
    "Save to watch later",
    "Prizes you have won",
    "",
    "",
    "",
    "",
    ""
  ];
}
